#!/bin/sh
#
# Copyright (c) 2013 mgm technology partners GmbH
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

ARGS="tasks"
if [ ! "x$1" = "x" ] ; then
	ARGS="$@"
fi

cd `dirname $0`
[ -f setenv.sh ] && . ./setenv.sh

echo "Initializing..."

exec ./gradlew --full-stactrace -I init.gradle -b Supervisor.gradle $ARGS
